postgrew_fdw: disable UPDATE or DELETE on a remote Greenplum cluster
Greenplum only supports INSERT, because UPDATE/DELETE SELECT requires
the hidden column gp_segment_id.

```
-- ===================================================================
-- test writable foreign table stuff
-- ===================================================================
INSERT INTO ft2 (c1,c2,c3)
  VALUES (1101,201,'aaa'), (1102,202,'bbb'), (1103,203,'ccc') RETURNING *;
  c1  | c2  | c3  | c4 | c5 | c6 |     c7     | c8
------+-----+-----+----+----+----+------------+----
 1101 | 201 | aaa |    |    |    | ft2        |
 1102 | 202 | bbb |    |    |    | ft2        |
 1103 | 203 | ccc |    |    |    | ft2        |
(3 rows)

UPDATE ft2 SET c2 = c2 + 300, c3 = c3 || '_update3' WHERE c1 % 10 = 3;
ERROR:  foreign table "ft2" does not allow updates
DELETE FROM ft2 WHERE c1 = 9999 RETURNING tableoid::regclass;
ERROR:  foreign table "ft2" does not allow deletes
```

Most of the UPDATE and DELETE cases are disabled, current status:

```
============== running regression test queries        ==============
test postgres_fdw             ... ok
test gp2gp                    ... ok
```