Fixed "ERROR:  latch already owned" after running 'kill -s QUIT ' on endpoint backend
This bug is found during adding test case at test4 in
src/test/isolation2/input/parallel_cursor/status.source.

- Symptom:

Run 'kill -s QUIT ' to kill endpoint backend,  if one endpoint has finished retrieving,
then this endpoint will issue below error during next time 'EXECUTE PARALLEL CURSOR':
ERROR:  latch already owned

- Solution:

For endpoint QE process, we should free all tokens run in this process
as EPR_SENDER when transaction end ( rollback or commit).

Here don't think about SubXact, because we only think the case that QD
has problem(which means the QE need to rollback the top transaction),
if QD works fine, it will send free token request by the
QD.